import { format } from 'date-fns'
import type Animal from '../../../schema/animal/Animal'
import type { AnimalAge } from '../../../util/AnimalUtility'
import type CareEvent from '../../../schema/care/CareEvent'
import type HealthRecord from '../../../schema/health/HealthRecord'
import type BreedingRecord from '../../../schema/breeding/BreedingRecord'
import type ProductionLog from '../../../schema/production/ProductionLog'
import type WeightLog from '../../../schema/weight/WeightLog'
import type Note from '../../../schema/notes/Note'
import type { WithdrawalResult } from '../../../util/WithdrawalUtility'
import type AnimalGroup from '../../../schema/animalGroup/AnimalGroup'
import { tstampToDate } from '../../../schema/type/Tstamp'
import { formatDate } from '../../../util/DateUtility'
import type { ExportData } from './IExportService'

export interface ExportParams extends ExportData {
  photoBase64?: string
}

function esc(text: string | number | undefined | null): string {
  if (text === undefined || text === null) return ''
  const s = String(text)
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function formatTstamp(tstamp: CareEvent['dueDate'] | null | undefined): string {
  const date = tstampToDate(tstamp)
  if (!date) return ''
  return format(date, 'MMM d, yyyy')
}

function styles(): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Helvetica, Arial, sans-serif; color: #333; padding: 24px; font-size: 11px; line-height: 1.4; }
    h1 { font-size: 20px; color: #2d5016; margin: 0 0 2px 0; }
    h2 { font-size: 14px; color: #4a6741; margin: 28px 0 8px 0; border-bottom: 2px solid #4a6741; padding-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    th { background: #f0f0eb; text-align: left; padding: 6px 8px; border: 1px solid #ddd; font-size: 10px; color: #555; text-transform: uppercase; letter-spacing: 0.3px; }
    td { padding: 6px 8px; border: 1px solid #ddd; font-size: 11px; vertical-align: top; }
    tr:nth-child(even) { background: #fafaf8; }
    .header { border-bottom: 2px solid #4a6741; padding-bottom: 12px; margin-bottom: 20px; }
    .header-sub { color: #666; font-size: 11px; margin: 2px 0; }
    .info-table { margin-bottom: 12px; }
    .info-table td { border: none; padding: 3px 8px; }
    .info-label { color: #666; font-weight: bold; width: 140px; white-space: nowrap; }
    .info-value { color: #333; }
    .footer { text-align: center; color: #999; font-size: 9px; margin-top: 32px; border-top: 1px solid #ddd; padding-top: 8px; }
    .photo { max-width: 180px; max-height: 180px; border-radius: 6px; margin: 8px 0; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; color: #fff; }
    .badge-own { background: #4caf50; }
    .badge-sold { background: #2196f3; }
    .badge-deceased { background: #e53935; }
    .badge-processed { background: #ff9800; }
    .empty { color: #999; font-style: italic; padding: 8px 0; }
    .withdrawal-active { color: #e65100; font-weight: bold; }
    .withdrawal-clear { color: #2e7d32; }
    .change-positive { color: #2e7d32; }
    .change-negative { color: #c62828; }
  `
}

function documentHeader(title: string, homesteadName: string): string {
  const today = format(new Date(), 'MMMM d, yyyy')
  return `
    <div class="header">
      <h1>${esc(title)}</h1>
      ${homesteadName ? `<p class="header-sub">${esc(homesteadName)}</p>` : ''}
      <p class="header-sub">Generated on ${today}</p>
    </div>
  `
}

function footer(): string {
  return '<div class="footer">Generated by Homestead App</div>'
}

function photoSection(photoBase64?: string): string {
  if (!photoBase64) return ''
  return `<img src="${photoBase64}" class="photo" />`
}

function infoRow(label: string, value: string | number): string {
  if (!value && value !== 0) return ''
  return `<tr><td class="info-label">${esc(label)}</td><td class="info-value">${esc(value)}</td></tr>`
}

function stateBadge(state: string): string {
  return `<span class="badge badge-${state}">${esc(state)}</span>`
}

function generalInfoSection(animal: Animal, age: AnimalAge): string {
  return `
    <h2>General Information</h2>
    <table class="info-table">
      ${infoRow('Name', animal.name)}
      ${infoRow('Type', animal.animalType)}
      ${infoRow('Breed', animal.breed)}
      ${infoRow('Gender', animal.gender)}
      ${infoRow('Birthday', formatDate(animal.birthday))}
      ${infoRow('Age', age.display)}
      ${infoRow('Color', animal.color)}
      ${infoRow('Registration #', animal.register)}
      <tr><td class="info-label">State</td><td class="info-value">${stateBadge(animal.state)}</td></tr>
      ${animal.purchasePrice > 0 ? infoRow('Purchase Price', `$${animal.purchasePrice.toFixed(2)}`) : ''}
      ${animal.weight > 0 ? infoRow('Current Weight', `${animal.weight} ${animal.weightUnit}`) : ''}
      ${infoRow('Notes', animal.notes)}
    </table>
  `
}

function getDosage(record: HealthRecord): string {
  if (record.recordType === 'medication' && record.medicationDosage > 0) {
    return `${record.medicationDosage} ${record.medicationDosageUnit}`
  }
  if (record.recordType === 'deworming' && record.dewormingDosage > 0) {
    return `${record.dewormingDosage} ${record.dewormingDosageUnit}`
  }
  return ''
}

function getRoute(record: HealthRecord): string {
  if (record.recordType === 'vaccination') return record.vaccineRoute || ''
  if (record.recordType === 'medication') return record.medicationRoute || ''
  if (record.recordType === 'deworming') return record.dewormingRoute || ''
  return ''
}

function getWithdrawalNote(record: HealthRecord): string {
  if (record.recordType === 'medication' && record.medicationWithdrawalDays > 0) {
    return `Withdrawal: ${record.medicationWithdrawalType} ${record.medicationWithdrawalDays}d`
  }
  if (record.recordType === 'deworming' && record.dewormingWithdrawalDays > 0) {
    return `Withdrawal: ${record.dewormingWithdrawalType} ${record.dewormingWithdrawalDays}d`
  }
  return ''
}

function healthRecordTypeName(type: string): string {
  const map: Record<string, string> = {
    vaccination: 'Vaccination',
    medication: 'Medication',
    deworming: 'Deworming',
    vetVisit: 'Vet Visit',
    illness: 'Illness',
    injury: 'Injury',
  }
  return map[type] || type
}

function healthRecordsSection(records: HealthRecord[]): string {
  const sorted = [...records].sort((a, b) => b.date.localeCompare(a.date))
  if (sorted.length === 0) {
    return '<h2>Health Records</h2><p class="empty">No health records.</p>'
  }
  const rows = sorted.map(r => {
    const notes = [r.notes, getWithdrawalNote(r)].filter(Boolean).join(' | ')
    return `
      <tr>
        <td>${esc(formatDate(r.date))}</td>
        <td>${esc(healthRecordTypeName(r.recordType))}</td>
        <td>${esc(r.name)}</td>
        <td>${esc(r.providerName)}</td>
        <td>${esc(getDosage(r))}</td>
        <td>${esc(getRoute(r))}</td>
        <td>${esc(notes)}</td>
        <td>${r.cost > 0 ? `$${r.cost.toFixed(2)}` : ''}</td>
      </tr>
    `
  }).join('')

  return `
    <h2>Health Records</h2>
    <table>
      <tr><th>Date</th><th>Type</th><th>Name</th><th>Provider</th><th>Dosage</th><th>Route</th><th>Notes</th><th>Cost</th></tr>
      ${rows}
    </table>
  `
}

function careEventsSection(events: CareEvent[]): string {
  const sorted = [...events].sort((a, b) => {
    const aDate = tstampToDate(a.dueDate)?.getTime() ?? 0
    const bDate = tstampToDate(b.dueDate)?.getTime() ?? 0
    return bDate - aDate
  })
  if (sorted.length === 0) {
    return '<h2>Care Events</h2><p class="empty">No care events.</p>'
  }
  const rows = sorted.map(e => {
    const typeName = e.type === 'careRecurring' ? 'Recurring' : 'Single'
    const cycle = e.type === 'careRecurring' && e.cycle > 0 ? `${e.cycle} days` : ''
    const contact = [e.contactName, e.contactPhone].filter(Boolean).join(' ')
    return `
      <tr>
        <td>${esc(e.name)}</td>
        <td>${esc(typeName)}</td>
        <td>${esc(cycle)}</td>
        <td>${esc(formatTstamp(e.dueDate))}</td>
        <td>${esc(formatTstamp(e.completedDate))}</td>
        <td>${esc(contact)}</td>
        <td>${esc(e.notes)}</td>
      </tr>
    `
  }).join('')

  return `
    <h2>Care Events</h2>
    <table>
      <tr><th>Name</th><th>Type</th><th>Cycle</th><th>Due Date</th><th>Completed</th><th>Contact</th><th>Notes</th></tr>
      ${rows}
    </table>
  `
}

function breedingRecordsSection(records: BreedingRecord[], animals: Animal[]): string {
  const sorted = [...records].sort((a, b) => b.breedingDate.localeCompare(a.breedingDate))
  if (sorted.length === 0) {
    return '<h2>Breeding Records</h2><p class="empty">No breeding records.</p>'
  }
  const rows = sorted.map(r => {
    const offspringNames = r.offspringIds
      .map(id => animals.find(a => a.id === id)?.name ?? id)
      .join(', ')
    return `
      <tr>
        <td>${esc(formatDate(r.breedingDate))}</td>
        <td>${esc(r.method)}</td>
        <td>${esc(r.sireName)}</td>
        <td>${esc(r.status)}</td>
        <td>${esc(formatDate(r.expectedDueDate))}</td>
        <td>${esc(formatDate(r.birthDate))}</td>
        <td>${r.bornAlive > 0 ? r.bornAlive : ''}</td>
        <td>${r.stillborn > 0 ? r.stillborn : ''}</td>
        <td>${esc(r.damCondition)}</td>
        <td>${esc(r.complications)}</td>
        <td>${esc(offspringNames)}</td>
      </tr>
    `
  }).join('')

  return `
    <h2>Breeding Records</h2>
    <table>
      <tr><th>Breeding Date</th><th>Method</th><th>Sire</th><th>Status</th><th>Expected Due</th><th>Birth Date</th><th>Born Alive</th><th>Stillborn</th><th>Dam Condition</th><th>Complications</th><th>Offspring</th></tr>
      ${rows}
    </table>
  `
}

function productionLogsSection(logs: ProductionLog[]): string {
  const sorted = [...logs].sort((a, b) => b.date.localeCompare(a.date))
  if (sorted.length === 0) {
    return '<h2>Production Logs</h2><p class="empty">No production logs.</p>'
  }
  const rows = sorted.map(l => `
    <tr>
      <td>${esc(formatDate(l.date))}</td>
      <td>${esc(l.productionType)}</td>
      <td>${l.quantity}</td>
      <td>${esc(l.unit)}</td>
      <td>${esc(l.notes)}</td>
    </tr>
  `).join('')

  return `
    <h2>Production Logs</h2>
    <table>
      <tr><th>Date</th><th>Type</th><th>Quantity</th><th>Unit</th><th>Notes</th></tr>
      ${rows}
    </table>
  `
}

interface WeightWithChange extends WeightLog {
  change: number
}

function weightHistorySection(logs: WeightLog[]): string {
  if (logs.length === 0) {
    return '<h2>Weight History</h2><p class="empty">No weight records.</p>'
  }
  const ascending = [...logs].sort((a, b) => a.date.localeCompare(b.date))
  const withChanges: WeightWithChange[] = ascending.map((log, i) => ({
    ...log,
    change: i > 0 ? log.weight - ascending[i - 1].weight : 0,
  }))
  withChanges.reverse()

  const rows = withChanges.map((w, i) => {
    const isLast = i === withChanges.length - 1
    let changeStr = ''
    let changeClass = ''
    if (!isLast) {
      const sign = w.change > 0 ? '+' : ''
      changeStr = `${sign}${w.change.toFixed(1)} ${w.weightUnit}`
      changeClass = w.change > 0 ? 'change-positive' : w.change < 0 ? 'change-negative' : ''
    }
    return `
      <tr>
        <td>${esc(formatDate(w.date))}</td>
        <td>${w.weight} ${esc(w.weightUnit)}</td>
        <td>${w.bodyConditionScore > 0 ? w.bodyConditionScore : ''}</td>
        <td class="${changeClass}">${changeStr}</td>
        <td>${esc(w.notes)}</td>
      </tr>
    `
  }).join('')

  return `
    <h2>Weight History</h2>
    <table>
      <tr><th>Date</th><th>Weight</th><th>Body Condition</th><th>Change</th><th>Notes</th></tr>
      ${rows}
    </table>
  `
}

function notesSection(notes: Note[]): string {
  const sorted = [...notes].sort((a, b) => {
    const aDate = tstampToDate(a.admin.created_at)?.getTime() ?? 0
    const bDate = tstampToDate(b.admin.created_at)?.getTime() ?? 0
    return bDate - aDate
  })
  if (sorted.length === 0) {
    return '<h2>Notes</h2><p class="empty">No notes.</p>'
  }
  const items = sorted.map(n => {
    const date = formatTstamp(n.admin.created_at)
    const tags = n.tags.length > 0 ? n.tags.join(', ') : ''
    return `
      <div style="margin-bottom: 10px; padding: 8px; border: 1px solid #eee; border-radius: 4px;">
        <div style="color: #666; font-size: 10px; margin-bottom: 4px;">
          ${esc(date)}${tags ? ` &mdash; ${esc(tags)}` : ''}
        </div>
        <div>${esc(n.text)}</div>
      </div>
    `
  }).join('')

  return `<h2>Notes</h2>${items}`
}

function withdrawalsSection(withdrawals: WithdrawalResult[]): string {
  if (withdrawals.length === 0) {
    return '<h2>Active Withdrawals</h2><p class="empty">No active withdrawals.</p>'
  }
  const rows = withdrawals.map(w => `
    <tr>
      <td>${esc(w.medicationName)}</td>
      <td>${esc(w.withdrawalType)}</td>
      <td>${esc(formatDate(w.withdrawalEndDate))}</td>
      <td class="withdrawal-active">${w.daysRemaining} days</td>
      <td class="withdrawal-active">${esc(w.status)}</td>
    </tr>
  `).join('')

  return `
    <h2>Active Withdrawals</h2>
    <table>
      <tr><th>Medication</th><th>Type</th><th>End Date</th><th>Days Remaining</th><th>Status</th></tr>
      ${rows}
    </table>
  `
}

function lineageSection(animal: Animal, animals: Animal[]): string {
  const sire = animal.sireId ? animals.find(a => a.id === animal.sireId) : null
  const dam = animal.damId ? animals.find(a => a.id === animal.damId) : null

  if (!sire && !dam) {
    return '<h2>Lineage</h2><p class="empty">No lineage information.</p>'
  }

  return `
    <h2>Lineage</h2>
    <table class="info-table">
      ${sire ? `<tr><td class="info-label">Sire</td><td class="info-value">${esc(sire.name)}${sire.register ? ` (#${esc(sire.register)})` : ''}</td></tr>` : ''}
      ${dam ? `<tr><td class="info-label">Dam</td><td class="info-value">${esc(dam.name)}${dam.register ? ` (#${esc(dam.register)})` : ''}</td></tr>` : ''}
    </table>
  `
}

function groupsSection(groups: AnimalGroup[]): string {
  if (groups.length === 0) {
    return '<h2>Group Memberships</h2><p class="empty">Not a member of any groups.</p>'
  }
  const items = groups.map(g => `<li>${esc(g.name)}</li>`).join('')
  return `<h2>Group Memberships</h2><ul style="margin: 8px 0 8px 20px;">${items}</ul>`
}

function wrapDocument(title: string, homesteadName: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>${styles()}</style></head>
<body>
  ${documentHeader(title, homesteadName)}
  ${body}
  ${footer()}
</body>
</html>`
}

export function buildCompleteRecordHtml(params: ExportParams): string {
  const body = [
    photoSection(params.photoBase64),
    generalInfoSection(params.animal, params.age),
    healthRecordsSection(params.healthRecords),
    careEventsSection(params.careEvents),
    breedingRecordsSection(params.breedingRecords, params.animals),
    productionLogsSection(params.productionLogs),
    weightHistorySection(params.weightLogs),
    notesSection(params.notes),
    withdrawalsSection(params.activeWithdrawals),
    lineageSection(params.animal, params.animals),
    groupsSection(params.groups),
  ].join('')
  return wrapDocument(`Complete Record — ${params.animal.name}`, params.homesteadName, body)
}

export function buildHealthCareSummaryHtml(params: ExportParams): string {
  const body = [
    photoSection(params.photoBase64),
    generalInfoSection(params.animal, params.age),
    healthRecordsSection(params.healthRecords),
    careEventsSection(params.careEvents),
    withdrawalsSection(params.activeWithdrawals),
  ].join('')
  return wrapDocument(`Health & Care Summary — ${params.animal.name}`, params.homesteadName, body)
}

export function buildBreedingLineageReportHtml(params: ExportParams): string {
  const body = [
    photoSection(params.photoBase64),
    generalInfoSection(params.animal, params.age),
    breedingRecordsSection(params.breedingRecords, params.animals),
    lineageSection(params.animal, params.animals),
  ].join('')
  return wrapDocument(`Breeding & Lineage Report — ${params.animal.name}`, params.homesteadName, body)
}

